### ISSUE TITLE
Install of all definitions fails / changing bower.json or package.json does nothing

### ISSUE THREAD

**Issue by torsten-sauer** [jvitor83/typings-autoinstaller#7]
I just installed the version 1.1.0 of this plugin but in effect it does nothing for me.

First I tried to install all definitions of all dependecies, but nothing happened. I opened the dev console and found following error:

> [Extension Host] TypeError: Cannot convert undefined or null to object
>     at TypingsService.install (C:\Users\torsten.sauer.vscode\extensions\jvitor83.typings-autoinstaller-1.1.0\out\src\TypingsService.js:10:38)
>     at installPackages (C:\Users\torsten.sauer.vscode\extensions\jvitor83.typings-autoinstaller-1.1.0\out\src\extension.js:108:20)
>     at C:\Users\torsten.sauer.vscode\extensions\jvitor83.typings-autoinstaller-1.1.0\out\src\extension.js:25:9
>     at Object.h [as _notify](c:Program Files %28x86%29Microsoft VS CoderesourcesappoutvsworkbenchnodeextensionHostProcess.js:5:13179)
>     at Object.__dirname.undefined.M.enter (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:5:16341)
>     at __dirname.undefined.t.Class.define._run (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:5:18167)
>     at __dirname.undefined.t.Class.define._completed (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:5:17608)
>     at e.resolveOk (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:10:14121)
>     at f (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:10:12603)
>     at _combinedTickCallback (internal/process/next_tick.js:67:7)

After that I tried to add something to bower.json and / or package.json and also nothing happened. No automatic installation of typings or addition to typings.

Any suggestions or ideas?

PS: I'm using Visual Studio Code 1.2.1 (Shell: 0.37.6, Render: 49.0.2623.75, Node: 5.10.0)

**Comment by torsten-sauer** [comment]
UPDATE:
After looking at the compiled code, I think I found a solution for the stacktrace:

**My package.json didn't contain a "dependencies" property (all packages I need are "devDependencies").**

I think you should check if (dev)dependencies exists, because the call leads to an error if the property isn't set (see https://github.com/jvitor83/typings-autoinstaller/blob/master/src/extension.ts#L125)

After adding an empty object, the process startet and installed the typings that were found. But adding something to bower.json or package.json don't work as intended,
